### ISSUE TITLE
[minor] Use camel case for parameters in configurations

### ISSUE THREAD

**Issue by JulesFrancoise** [Ircam-RnD/xmm-node#2]
`relative_regularization` => `relativeRegularization`
`absolute_regularization` => `absoluteRegularization`
`covariance_mode` => `covarianceMode`
`transition_mode` => `transitionMode`
`regression_estimator` => `regressionEstimator`

**Comment by josephlarralde** [comment]
Yes, I originally wanted to stick to the C++ API but Benjamin Matuszewski gave me exactly the same advice. I'll go back to working on the develop branch and add this feature for the next release (as well as other improvements to the C++ code). Thanks for confirming

**Comment by josephlarralde** [comment]
Done ! (old style underscore still works but is not documented anymore)
